language : php
php :
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_install: true

install :
  - composer install

before_script: true

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - docker run -v $(pwd):/app --rm phpunit/phpunit run tests

after_script: true


deploy:
  provider: heroku
  api_key:

