langage: 'php'
php: '7.3' 

cache: 
    directories:
        -$HOME/.composer/cache
before install: true

install: 
- composer install

before script : true

script: 
  - phpunit tests
  - .vendor/bin/php-cs-fixer fix —dry-run 

after script: true
