langage: 'php'
php: '7.3' 

cache: 
    directories:
        - "$HOME/.composer/cache"
before install: true

install: 
- composer install

before script : true

script: 
 # - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
  - docker run -v $PWD:/app -w /app php:7.3-cli  "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
  - phpunit tests

after script: true

